language: android
dist: trusty
android:
  components:
    # The BuildTools version used by your project
    - build-tools-30.0.0
    # The SDK version used to compile your project
    - android-29
    # Additional components
    - extra-android-m2repository
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-29
    # - sys-img-armeabi-v7a-android-17
jdk:
   - oraclejdk8
before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-27"
script:
  - ./gradlew build connectedCheck